diff --git a/Makefile b/Makefile
index abe2a4f..486d53f 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 EXTRA_CFLAGS += -Werror -DCONFIG_MT76_LEDS
 
 obj-m := mt76.o
-obj-$(CONFIG_MT7603E) += mt7603/
+obj-m += mt7603/
 obj-$(CONFIG_MT76x02_LIB) += mt76x02-lib.o
 obj-$(CONFIG_MT76x02_USB) += mt76x02-usb.o
 obj-$(CONFIG_MT76_USB) += mt76-usb.o
@@ -19,3 +19,15 @@ mt76x02-lib-y := mt76x02_util.o mt76x02_mac.o mt76x02_mcu.o \
 		 mt76x02_dfs.o
 
 mt76x02-usb-y := mt76x02_usb_mcu.o mt76x02_usb_core.o
+
+SRC := $(shell pwd)
+
+all:
+	$(MAKE) -C $(KERNEL_SRC) M=$(SRC)
+
+modules_install:
+	$(MAKE) -C $(KERNEL_SRC) M=$(SRC) modules_install
+clean:
+	@rm *.o || true
+
+
